import { AboutSlint, Button, VerticalBox } from "std-widgets.slint";


export component AppWindow inherits Window {
    no-frame: true;
    width: 1200px;
    height: 800px;
    Rectangle {
        width: 1200px;
        height: 800px;
        background: #FF3900;

        VerticalLayout {
            y: 100px;
            spacing: 20px;
            Rectangle {
                 Image {
                    source: @image-url("../assets/logo-allhands.png");
                }
            }

            Rectangle {
                Text {
                    font-size: 50px;
                    horizontal-alignment: center;
                    text: "THINK YOU’VE GOT WHAT IT TAKES TO BE A BETWARRIOR EXPERT?";
                    color: white;
                    wrap: word-wrap;
                    width: 50%;
                    font-family: "Bebas Neue";
                    font-weight: 800;
                }
                
            }
            Rectangle {
                Text {
                    font-size: 50px;
                    horizontal-alignment: center;
                    text: "SCAN YOUR WRISTBAND TO START!";
                    color: white;
                    wrap: word-wrap;
                    width: 50%;
                    font-family: "Bebas Neue";
                    font-weight: 800;
                }
            }

            Rectangle {
                 Path {
                    width: 180px;
                    height: 150px;
                    commands: "M11 5V-14A1 1 0 007-14V5L3 0A1 1 0 001 2L8 10C9 11 9 11 10 10L17 2A1 1 0 0015 0L11 5";
                    stroke: black;
                    stroke-width: 10px;
                    fill: black;
                    stroke-line-cap: round;
                }
            }


        }
       
       
    
    }
    
       
    }

       
