import { VerticalBox } from "std-widgets.slint";
import { Logo } from "Logo.slint";

export component PreintroScreen inherits Rectangle {
    width: 1080px;
    height: 1980px;
    background: #FF3900; // Ensure consistent background

    // Logo with absolute positioning
    Logo {
        x: (parent.width - 800px) / 2; // Center horizontally
        y: 100px; // 20px from top
    }

    // Content in VerticalLayout, starting below logo
    VerticalLayout {
        width: parent.width;
        spacing: 100px;
        padding: 20px;
        alignment: center;

        

        // Challenge text
        Rectangle {
            width: parent.width;
            height: 200px;
            background: #FF3900;
            Text {
                text: "¡PARTICIPÁ DE LAS TRIVIAS  Y SUMÁ PUNTOS!";
                font-size: 73px;
                font-weight: 800;
                horizontal-alignment: center;
                vertical-alignment: center;
                color: white;
                wrap: word-wrap;
                width: 80%;
                font-family: "Montserrat";
            }
        }

        // Instruction text
        Rectangle {
            width: parent.width;
            height: 200px;
            background: #FF3900;
            Text {
                text: "ESCANEÁ TU PULSERA PARA PARTICIPAR ";
                font-size: 73px;
                font-weight: 800;
                horizontal-alignment: center;
                vertical-alignment: center;
                color: white;
                wrap: word-wrap;
                width: 80%;
                font-family: "Montserrat";
            }
        }

        // Downward arrow
        VerticalLayout {
            padding-top: 150px;
            Rectangle {
            width: parent.width;
            height: 300px;
            background: #FF3900;
            Path {
                width: 312px;
                height: 437px;
                commands: "M22 10V-28A2 2 0 0014-28V10L6 0A2 2 0 002 4L17 22C18 23 18 23 19 22L34 4A2 2 0 0030 0L22 10";
                stroke: black;
                stroke-width: 10px;
                fill: black;
                stroke-line-cap: round;
                x: (parent.width - self.width) / 2;
                y: (parent.height - self.height) / 2 + 100px;
            }
        }
        }
    }
}